const ACTION_TYPES = {
  UPDATE_NEW_POST_TEXT: "UPDATE_NEW_POST_TEXT",
  ADD_POST: "ADD_POST",
  UPDATE_NEW_MESSAGE_BODY: "UPDATE_NEW_MESSAGE_BODY",
  SEND_MESSAGE: "SEND_MESSAGE",
  FOLLOW_TO_USER:"FOLLOW_TO_USER",
  UNFOLLOW_TO_USER: "UNFOLLOW_TO_USER",
  SET_USERS: "SET_USERS"
};

export default ACTION_TYPES;