const ACTION_TYPES = {
  ADD_POST: "ADD_POST",
  DELETE_POST: "DELETE_POST",
  SEND_MESSAGE: "SEND_MESSAGE",
  FOLLOW_TO_USER:"FOLLOW_TO_USER",
  UNFOLLOW_TO_USER: "UNFOLLOW_TO_USER",
  SET_USERS: "SET_USERS",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SET_TOTAL_USERS_COUNT: "SET_TOTAL_USERS_COUNT",
  TOGGLE_IS_FETCHINE: "TOGGLE_IS_FETCHINE",
  SET_USER_PROFILE: "SET_USER_PROFILE",
  SET_USER_DATA: "SET_USER_DATA",
  SET_STATUS: "SET_STATUS",
  SAVE_PHOTO_SUC: "SAVE_PHOTO_SUC"
};

export default ACTION_TYPES;